#!/usr/bin/env python3
"""Validate the mobile Patient Monitor UX parity contract.

This is intentionally a source-level guard.  The SwiftUI app is generated by
XcodeGen and exercised through UITests, while this script catches the cheap,
high-value contract drift that triggered issues #12-#17.
"""

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "App" / "Sources" / "MobilePodModel.swift"
VIEW = ROOT / "App" / "Sources" / "ContentView.swift"
POD_VIEW = ROOT / "App" / "Sources" / "MobilePodManagementView.swift"
UITEST = ROOT / "App" / "UITests" / "SeededFlowUITests.swift"


def require(text: str, needle: str, label: str, errors: list[str]) -> None:
    if needle not in text:
        errors.append(f"missing {label}: {needle}")


def main() -> int:
    model = MODEL.read_text()
    view = VIEW.read_text()
    pod_view = POD_VIEW.read_text()
    uitest = UITEST.read_text()
    combined = "\n".join([model, view, pod_view, uitest])

    errors: list[str] = []

    for domain in [
        "profiles",
        "conditions",
        "medications",
        "allergies",
        "immunizations",
        "vital-signs",
        "providers",
        "lab-results",
        "insurance-policies",
        "documents",
        "workflow-tasks",
    ]:
        require(model, f'"{domain}"', f"11-domain PIM contract member {domain}", errors)

    for vital_node in [
        "blood-pressure",
        "heart-rate",
        "body-temperature",
        "oxygen-saturation",
        "body-weight",
        "bmi",
    ]:
        require(combined, vital_node, f"PIM Vitals semantic node {vital_node}", errors)

    for system in [
        "http://loinc.org",
        "http://www.nlm.nih.gov/research/umls/rxnorm",
        "http://snomed.info/sct",
        "http://hl7.org/fhir/sid/cvx",
    ]:
        require(model, system, f"coding system URL {system}", errors)

    require(model, "defaultOwnerStorageIRI = \"http://css.localhost:13000/jateeter/\"", "local owner Pod default", errors)
    if "localhost:13000/alice" in model:
        errors.append("placeholder alice Pod default must not be reintroduced")

    for affordance in [
        "PatientOwnerMenu",
        "DailyTimeline",
        "DailyActivity-morning-medications",
        "Stage for owner review",
        "PatientPrivacyTermsLink",
        "PatientPrivacyDisclosureLink",
        "PodTermsLink",
        "PodDataDisclosureLink",
    ]:
        require(combined, affordance, f"mobile UX affordance {affordance}", errors)

    require(model, "refreshLocalPIMStatus", "live PIM/CSS status binding", errors)
    require(model, "stagedData", "durable staged owner draft queue", errors)
    require(model, "mobileSolid.stagedData", "UserDefaults-backed staged data", errors)

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print("Mobile PIM parity contract validated for issues #12-#17.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
